### ISSUE TITLE
Fatal Error same as others 

### ISSUE THREAD

**Issue by zephzeph** [oasisprotocol/oasis-wallet-web#479] opened 2021-11-29 17:41 UTC
NetworkError when attempting to fetch resource.
The above error occurred in task vr
    created by vr
    created by takeEvery(account/fetchAccount, vr)
    created by xr
Tasks cancelled due to error:
takeEvery(account/fetchAccount, vr)
Or

**Comment by matevz** [comment] 2021-11-30 12:09
Oasis monitor was down yesterday. Duplicate of #403. Reopen, if error still persists today please.

**Closed by matevz** 2021-11-30 12:09 UTC
Labels: duplicate
