### ISSUE TITLE
help me recover my stalked wallet

### ISSUE THREAD

**Issue by dmack6945** [oasisprotocol/oasis-wallet-web#388] opened 2021-11-04 01:31 UTC
The above error occurred in task Za
    created by Xa
    created by takeEvery(staking/fetchAccount, Xa)
    created by er
Tasks cancelled due to error:
takeEvery(staking/fetchAccount, Xa)
takeEvery(staking/validatorSelected, Qa)

**Comment by matevz** [comment] 2021-11-04 10:02
Duplicate of https://github.com/oasisprotocol/oasis-wallet-web/issues/403

**Closed by matevz** 2021-11-04 10:02 UTC
Labels: duplicate
