### ISSUE TITLE
Error opening wallet

### ISSUE THREAD

**Issue by francbonet** [oasisprotocol/oasis-wallet-web#405] opened 2021-11-04 10:22 UTC
undefined
The above error occurred in task Za
    created by Xa
    created by takeEvery(staking/fetchAccount, Xa)
    created by er
Tasks cancelled due to error:
takeEvery(staking/fetchAccount, Xa)
takeEvery(staking/validatorSelected, Qa)
undefined

**Comment by matevz** [comment] 2021-11-04 11:34
Duplicate of #403

**Closed by matevz** 2021-11-04 11:34 UTC
Labels: duplicate
