### ISSUE TITLE
Error my wallet 

### ISSUE THREAD

**Issue by Ciro7777** [oasisprotocol/oasis-wallet-web#386] opened 2021-11-04 00:11 UTC
Hello, I have sent my rose to my binance account and I have not received anything, but if the transfer is made in oasisscan because of your wallet, I have sent it as staking and now binance does not read it to me, please help me. 

undefined
The above error occurred in task Za
    created by Xa
    created by takeEvery(staking/fetchAccount, Xa)
    created by er
Tasks cancelled due to error:
takeEvery(staking/fetchAccount, Xa)
takeEvery(staking/validatorSelected, Qa)
undefined

**Comment by manasundae** [comment] 2021-11-04 00:43
Ive got the same error

undefined
The above error occurred in task Za
    created by Xa
    created by takeEvery(staking/fetchAccount, Xa)
    created by er
Tasks cancelled due to error:
takeEvery(staking/fetchAccount, Xa)
takeEvery(staking/validatorSelected, Qa)
undefined

**Comment by itchgamer** [comment] 2021-11-04 00:53
Same here!!!

**Comment by cryptoleekwu** [comment] 2021-11-04 01:31
undefined
The above error occurred in task Za
    created by Xa
    created by takeEvery(staking/fetchAccount, Xa)
    created by er
Tasks cancelled due to error:
takeEvery(staking/fetchAccount, Xa)
takeEvery(staking/validatorSelected, Qa)
undefined

**Comment by jim1982111** [comment] 2021-11-04 03:44
I've got the same error too. Surprised the devs havent said anything it seems like a lot of people are experiencing this right now.

**Comment by pro-wh** [comment] 2021-11-04 05:09
same here, experiencing this on Firefox on Windows.

right after I created a new wallet

I'm seeing an http 500 on https://monitor.oasis.dev/data/validators. maybe that's related? can't tell from the obfuscated stack

**Comment by tendiemanncommeth** [comment] 2021-11-04 06:20
I have this issue on brave browser and that new MS one whats it called edge?

undefined
The above error occurred in task Za
    created by Xa
    created by takeEvery(staking/fetchAccount, Xa)
    created by er
Tasks cancelled due to error:
takeEvery(staking/fetchAccount, Xa)
takeEvery(staking/validatorSelected, Qa)
undefined

**Comment by matevz** [comment] 2021-11-04 09:59
Duplicate of https://github.com/oasisprotocol/oasis-wallet-web/issues/403

**Closed by matevz** 2021-11-04 09:59 UTC
