### ISSUE TITLE
Unable to load validators when staking

### ISSUE THREAD

**Issue by ReddropAsh** [oasisprotocol/oasis-wallet-web#572] opened 2022-01-08 01:05 UTC
After opening the wallet the stake tab displays

Validators

Couldn't load transactions. List may be empty or out of date. Error: request https://monitor.oasis.dev/data/validators?limit=500 status 500

Unable to manage staking

**Comment by pro-wh** [comment] 2022-01-08 02:09
I've filed an issue for a potential cause

https://github.com/everstake/oasis-explorer/issues/33

**Comment by kjniedz** [comment] 2022-01-08 16:09
I've been experiencing a similar issue this morning with the staking tab, unable to manage staking / can't load transactions. 

Error: https://monitor.oasis.dev/data/validators?limit=500 status 500

json: unsupported value: NaN

**Comment by k-bailey** [comment] 2022-01-08 23:55
same issue here

**Comment by oiolor** [comment] 2022-01-09 17:06
so do i

**Comment by Ryannguyen1993** [comment] 2022-01-10 06:13
Same issue here! Couldn't load delegations and stake.

**Comment by danen-carlson** [comment] 2022-01-10 18:09
Same Issue here.

**Comment by liorpinsky** [comment] 2022-01-11 21:14
same issue. anyone knows how to resolve this?

**Comment by matevz** [comment] 2022-01-14 08:19
Oasis monitor was up and down in the last days. Duplicate of #403. We are working on this.

**Closed by matevz** 2022-01-14 08:19 UTC
