### ISSUE TITLE
Hello, this message appears when i try to unlock my oasis wallet

### ISSUE THREAD

**Issue by Selmarils** [oasisprotocol/oasis-wallet-web#464] opened 2021-11-29 16:45 UTC
Failed to fetch
The above error occurred in task vr
    created by vr
    created by takeEvery(account/fetchAccount, vr)
    created by xr
Tasks cancelled due to error:
takeEvery(account/fetchAccount, vr)
Or
TypeError: Failed to fetch
    at fetchCallImpl (https://gc.kis.v2.scr.kaspersky-labs.com/FD126C42-EBFA-4E12-B309-BB3FDD723AC1/main.js?attr=5gNI1AVp_ZLmDAlGDShERf_dl-MnZCGQJ2vWtqCrkgZdkTFNOg7mFXpgR-CHXkhBndTueay750P1HXrQzDv_4w:2671:25)
    at window.fetch (https://gc.kis.v2.scr.kaspersky-labs.com/FD126C42-EBFA-4E12-B309-BB3FDD723AC1/main.js?attr=5gNI1AVp_ZLmDAlGDShERf_dl-MnZCGQJ2vWtqCrkgZdkTFNOg7mFXpgR-CHXkhBndTueay750P1HXrQzDv_4w:2673:55)
    at https://wallet.oasisprotocol.org/static/js/main.1cb68546.chunk.js:1:5921
    at f (https://wallet.oasisprotocol.org/static/js/2.48cea8b1.chunk.js:2:490496)
    at Generator._invoke (https://wallet.oasisprotocol.org/static/js/2.48cea8b1.chunk.js:2:490284)
    at Generator.next (https://wallet.oasisprotocol.org/static/js/2.48cea8b1.chunk.js:2:490921)
    at n (https://wallet.oasisprotocol.org/static/js/2.48cea8b1.chunk.js:2:44538)
    at u (https://wallet.oasisprotocol.org/static/js/2.48cea8b1.chunk.js:2:44741)
    at https://wallet.oasisprotocol.org/static/js/2.48cea8b1.chunk.js:2:44800
    at new Promise (<anonymous>)

**Comment by matevz** [comment] 2021-11-30 12:12
Oasis monitor was down yesterday. Duplicate of #403. Reopen, if error still persists today please.

**Closed by matevz** 2021-11-30 12:12 UTC
Labels: duplicate
