### ISSUE TITLE
Wallet error - cannot access

### ISSUE THREAD

**Issue by itchgamer** [oasisprotocol/oasis-wallet-web#387] opened 2021-11-04 00:51 UTC
Hello,

Everytime I try to open my wallet I receive the following error message:

The above error occurred in task Za
    created by Xa
    created by takeEvery(staking/fetchAccount, Xa)
    created by er
Tasks cancelled due to error:
takeEvery(staking/fetchAccount, Xa)
takeEvery(staking/validatorSelected, Qa)

**Comment by matevz** [comment] 2021-11-04 09:59
Duplicate of https://github.com/oasisprotocol/oasis-wallet-web/issues/403

**Closed by matevz** 2021-11-04 09:59 UTC
Labels: duplicate
