### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by MadhDogh** [oasisprotocol/oasis-wallet-web#460] opened 2021-11-29 16:33 UTC
Hi, 

I have an issue with Oasis Wallet on Firefox. I tried several times to open it with seed phrase and still have this error: 

NetworkError when attempting to fetch resource.
The above error occurred in task vr
    created by vr
    created by takeEvery(account/fetchAccount, vr)
    created by xr
Tasks cancelled due to error:
takeEvery(account/fetchAccount, vr)
Or

I tried too on Brave and i had this error:

Failed to fetch
The above error occurred in task vr
    created by vr
    created by takeEvery(account/fetchAccount, vr)
    created by xr
Tasks cancelled due to error:
takeEvery(account/fetchAccount, vr)
Or
TypeError: Failed to fetch
    at https://wallet.oasisprotocol.org/static/js/main.1cb68546.chunk.js:1:5921
    at f (https://wallet.oasisprotocol.org/static/js/2.48cea8b1.chunk.js:2:490496)
    at Generator._invoke (https://wallet.oasisprotocol.org/static/js/2.48cea8b1.chunk.js:2:490284)
    at Generator.next (https://wallet.oasisprotocol.org/static/js/2.48cea8b1.chunk.js:2:490921)
    at n (https://wallet.oasisprotocol.org/static/js/2.48cea8b1.chunk.js:2:44538)
    at u (https://wallet.oasisprotocol.org/static/js/2.48cea8b1.chunk.js:2:44741)
    at https://wallet.oasisprotocol.org/static/js/2.48cea8b1.chunk.js:2:44800
    at new Promise (<anonymous>)
    at n.<anonymous> (https://wallet.oasisprotocol.org/static/js/2.48cea8b1.chunk.js:2:44681)
    at n.fetchApi (https://wallet.oasisprotocol.org/static/js/main.1cb68546.chunk.js:1:6510)

What can i do?

**Comment by meliodas880** [comment] 2021-11-29 16:36
i have the same propblem

**Comment by meliodas880** [comment] 2021-11-29 16:36
Failed to fetch
The above error occurred in task vr
    created by vr
    created by takeEvery(account/fetchAccount, vr)
    created by xr
Tasks cancelled due to error:
takeEvery(account/fetchAccount, vr)
Or
TypeError: Failed to fetch
    at https://wallet.oasisprotocol.org/static/js/main.1cb68546.chunk.js:1:5921
    at f (https://wallet.oasisprotocol.org/static/js/2.48cea8b1.chunk.js:2:490496)
    at Generator._invoke (https://wallet.oasisprotocol.org/static/js/2.48cea8b1.chunk.js:2:490284)
    at Generator.next (https://wallet.oasisprotocol.org/static/js/2.48cea8b1.chunk.js:2:490921)
    at n (https://wallet.oasisprotocol.org/static/js/2.48cea8b1.chunk.js:2:44538)
    at u (https://wallet.oasisprotocol.org/static/js/2.48cea8b1.chunk.js:2:44741)
    at https://wallet.oasisprotocol.org/static/js/2.48cea8b1.chunk.js:2:44800
    at new Promise (<anonymous>)
    at n.<anonymous> (https://wallet.oasisprotocol.org/static/js/2.48cea8b1.chunk.js:2:44681)
    at n.fetchApi (https://wallet.oasisprotocol.org/static/js/main.1cb68546.chunk.js:1:6510)

**Comment by pro-wh** [comment] 2021-11-30 00:55
Regarding this and similar reports: we're working on making some of the functionality still work even when the block explorer APIs are down.

**Comment by matevz** [comment] 2021-11-30 12:14
Yep, Oasis monitor was down yesterday. Duplicate of #403. Reopen, if error still persists today please.

**Closed by matevz** 2021-11-30 12:14 UTC
