### ISSUE TITLE
fatal error opening my wallet

### ISSUE THREAD

**Issue by stressreelief** [oasisprotocol/oasis-wallet-web#389] opened 2021-11-04 01:51 UTC
undefined
The above error occurred in task Za
    created by Xa
    created by takeEvery(staking/fetchAccount, Xa)
    created by er
Tasks cancelled due to error:
takeEvery(staking/fetchAccount, Xa)
takeEvery(staking/validatorSelected, Qa)
undefined

**Comment by stressreelief** [comment] 2021-11-04 01:52
can you please send me an e-mail if this is rectified . I am deeply concerned . Thank you , john 
stressreelief@hotmail.com

**Comment by tendiemanncommeth** [comment] 2021-11-04 06:18
I got same issue

undefined
The above error occurred in task Za
    created by Xa
    created by takeEvery(staking/fetchAccount, Xa)
    created by er
Tasks cancelled due to error:
takeEvery(staking/fetchAccount, Xa)
takeEvery(staking/validatorSelected, Qa)
undefined

**Comment by matevz** [comment] 2021-11-04 09:58
Duplicate of https://github.com/oasisprotocol/oasis-wallet-web/issues/403

**Closed by matevz** 2021-11-04 09:58 UTC
Labels: duplicate
