### ISSUE TITLE
Oasis wallet, A fatal error occurred

### ISSUE THREAD

**Issue by fagrg44** [oasisprotocol/oasis-wallet-web#485] opened 2021-11-29 18:39 UTC
A fatal unexpected error has occurred and Oasis-wallet must stop. Please copy report this issue below on our github account. You can also try refreshing page to see if the issue persists. Once you leave this page, all of your wallets will be closed.
---------------------------------------------------------------------------------------------------------------------------------------------------

request https://monitor.oasis.dev/data/transactions?account_id=oasis1qq6v73y25axdysk6g5zpfypf97hg80g8kyw6uvug status 500
The above error occurred in task vr
    created by vr
    created by takeEvery(account/fetchAccount, vr)
    created by xr
Tasks cancelled due to error:
takeEvery(account/fetchAccount, vr)
Or
Error: request https://monitor.oasis.dev/data/transactions?account_id=oasis1qq6v73y25axdysk6g5zpfypf97hg80g8kyw6uvug status 500
    at n.<anonymous> (https://wallet.oasisprotocol.org/static/js/main.1cb68546.chunk.js:1:7482)
    at f (https://wallet.oasisprotocol.org/static/js/2.48cea8b1.chunk.js:2:490496)
    at Generator._invoke (https://wallet.oasisprotocol.org/static/js/2.48cea8b1.chunk.js:2:490284)
    at Generator.next (https://wallet.oasisprotocol.org/static/js/2.48cea8b1.chunk.js:2:490921)
    at n (https://wallet.oasisprotocol.org/static/js/2.48cea8b1.chunk.js:2:44538)
    at u (https://wallet.oasisprotocol.org/static/js/2.48cea8b1.chunk.js:2:44741)

**Comment by matevz** [comment] 2021-11-30 12:13
Oasis monitor was down yesterday. Duplicate of #403. Reopen, if error still persists today please.

**Closed by matevz** 2021-11-30 12:13 UTC
Labels: duplicate
