### ISSUE TITLE
Http response at 400 or 500 level error in task Ja

### ISSUE THREAD

**Issue by clipchak** [oasisprotocol/oasis-wallet-web#504] opened 2021-12-02 16:25 UTC
Http response at 400 or 500 level
The above error occurred in task Ja
    created by Xa
    created by Xa
    created by takeEvery(staking/fetchAccount, Xa)
    created by er
Tasks cancelled due to error:
takeEvery(staking/fetchAccount, Xa)
takeEvery(staking/validatorSelected, Qa)

**Comment by clipchak** [comment] 2021-12-02 16:30
thankfully i had my private key written down and could reopen my wallet or else this error would have locked me out of my funds for good

**Comment by matevz** [comment] 2022-01-14 08:22
Oasis monitor was up and down in the last days. Duplicate of #403. We are working on this.

**Closed by matevz** 2022-01-14 08:22 UTC
