### ISSUE TITLE
Error: Http response at 400 or 500 level

### ISSUE THREAD

**Issue by lmgs007** [oasisprotocol/oasis-wallet-web#583] opened 2022-01-11 18:24 UTC
Error: Http response at 400 or 500 level

The above error occurred in task selectNetwork
    created by takeEvery(network/selectNetwork, selectNetwork)
    created by networkSaga
Tasks cancelled due to error:
takeEvery(network/selectNetwork, selectNetwork)

E@https://wallet.oasisprotocol.org/static/js/2.5535bd8c.chunk.js:94905:17
Y@https://wallet.oasisprotocol.org/static/js/2.5535bd8c.chunk.js:96430:38
@https://wallet.oasisprotocol.org/static/js/2.5535bd8c.chunk.js:96404:26
Ib@https://wallet.oasisprotocol.org/static/js/2.5535bd8c.chunk.js:95551:26
O@https://wallet.oasisprotocol.org/static/js/2.5535bd8c.chunk.js:95537:5
wc@https://wallet.oasisprotocol.org/static/js/2.5535bd8c.chunk.js:96058:22
yc@https://wallet.oasisprotocol.org/static/js/2.5535bd8c.chunk.js:96125:11
@https://wallet.oasisprotocol.org/static/js/2.5535bd8c.chunk.js:96070:5
@https://wallet.oasisprotocol.org/static/js/2.5535bd8c.chunk.js:96066:60
@[native code]

**Comment by lmgs007** [comment] 2022-01-11 22:49
Hello, good afternoon, any comments to understand the error that occurred

Thank you

Greetings

**Comment by matevz** [comment] 2022-01-14 08:20
Oasis monitor was up and down in the last days. Duplicate of #403. We are working on this.

**Closed by matevz** 2022-01-14 08:20 UTC
