### ISSUE TITLE
Failure to load wallet

### ISSUE THREAD

**Issue by Rainbow0111** [oasisprotocol/oasis-wallet-web#478] opened 2021-11-29 17:41 UTC
Http response at 400 or 500 level
The above error occurred in task ft
    created by takeEvery(network/selectNetwork, ft)
    created by ht
Tasks cancelled due to error:
takeEvery(network/selectNetwork, ft)
Error: Http response at 400 or 500 level
    at new D (https://wallet.oasisprotocol.org/static/js/2.48cea8b1.chunk.js:2:1047878)
    at Ft (https://wallet.oasisprotocol.org/static/js/2.48cea8b1.chunk.js:2:1070696)
    at _t.<anonymous> (https://wallet.oasisprotocol.org/static/js/2.48cea8b1.chunk.js:2:1069926)
    at Ue (https://wallet.oasisprotocol.org/static/js/2.48cea8b1.chunk.js:2:1056709)
    at Be (https://wallet.oasisprotocol.org/static/js/2.48cea8b1.chunk.js:2:1056515)
    at xt (https://wallet.oasisprotocol.org/static/js/2.48cea8b1.chunk.js:2:1064004)
    at Tt (https://wallet.oasisprotocol.org/static/js/2.48cea8b1.chunk.js:2:1064785)
    at _t.r.W (https://wallet.oasisprotocol.org/static/js/2.48cea8b1.chunk.js:2:1065726)
    at _t.r.R (https://wallet.oasisprotocol.org/static/js/2.48cea8b1.chunk.js:2:1065705)

**Comment by matevz** [comment] 2021-11-30 12:10
Oasis monitor was down yesterday. Duplicate of #403. Reopen, if error still persists today please.

**Closed by matevz** 2021-11-30 12:10 UTC
Labels: duplicate
