### ISSUE TITLE
what this

### ISSUE THREAD

**Issue by maslakh** [oasisprotocol/oasis-wallet-web#462] opened 2021-11-29 16:38 UTC
Failed to fetch
The above error occurred in task vr
    created by vr
    created by takeEvery(account/fetchAccount, vr)
    created by xr
Tasks cancelled due to error:
takeEvery(account/fetchAccount, vr)
Or
TypeError: Failed to fetch
    at https://wallet.oasisprotocol.org/static/js/main.1cb68546.chunk.js:1:5921
    at f (https://wallet.oasisprotocol.org/static/js/2.48cea8b1.chunk.js:2:490496)
    at Generator._invoke (https://wallet.oasisprotocol.org/static/js/2.48cea8b1.chunk.js:2:490284)
    at Generator.next (https://wallet.oasisprotocol.org/static/js/2.48cea8b1.chunk.js:2:490921)
    at n (https://wallet.oasisprotocol.org/static/js/2.48cea8b1.chunk.js:2:44538)
    at u (https://wallet.oasisprotocol.org/static/js/2.48cea8b1.chunk.js:2:44741)
    at https://wallet.oasisprotocol.org/static/js/2.48cea8b1.chunk.js:2:44800
    at new Promise (<anonymous>)
    at n.<anonymous> (https://wallet.oasisprotocol.org/static/js/2.48cea8b1.chunk.js:2:44681)
    at n.fetchApi (https://wallet.oasisprotocol.org/static/js/main.1cb68546.chunk.js:1:6510)

**Comment by matevz** [comment] 2021-11-30 12:13
Oasis monitor was down yesterday. Duplicate of #403. Reopen, if error still persists today please.

**Closed by matevz** 2021-11-30 12:13 UTC
Labels: duplicate
