### ISSUE TITLE
me sigue dando error al intentar abrir wuallet

### ISSUE THREAD

**Issue by jota0164** [oasisprotocol/oasis-wallet-web#404] opened 2021-11-04 10:03 UTC
undefined
The above error occurred in task Za
    created by Xa
    created by takeEvery(staking/fetchAccount, Xa)
    created by er
Tasks cancelled due to error:
takeEvery(staking/fetchAccount, Xa)
takeEvery(staking/validatorSelected, Qa)
undefined

**Comment by matevz** [comment] 2021-11-04 11:35
Duplicate of #403

**Closed by matevz** 2021-11-04 11:35 UTC
Labels: duplicate

**Comment by jota0164** [comment] 2021-11-04 11:38
Oki.
Gracias ..sigo a la espera de la activación.
Un saludo
