### ISSUE TITLE
Add a way to reclaim all escrow shares

### ISSUE THREAD

**Issue by Yawning** [oasisprotocol/oasis-wallet-web#503] opened 2021-12-02 15:45 UTC
Because the web wallet converts from ROSE when determining how many tokens to withdraw, it is possible to be left with a delegation that is worth an infinitesimally small amount of ROSE.  As the amount delegated is less than a share, no rewards are generated, and this spams the account with 0 token staking rewards, as well as leaving a worthless delegation stuck in the metadata.

The web wallet badly needs a way to reclaim all shares, that actually fully reclaims everything.

**Comment by matevz** [comment] 2022-01-14 08:23
This is actually duplicate of #492 :wink:

**Closed by matevz** 2022-01-14 08:23 UTC
Labels: ui
