### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Randysailer** [oasisprotocol/oasis-wallet-web#390] opened 2021-11-04 03:17 UTC
undefined The above error occurred in task Za created by Xa created by takeEvery(staking/fetchAccount, Xa) created by er Tasks cancelled due to error: takeEvery(staking/fetchAccount, Xa) takeEvery(staking/validatorSelected, Qa) undefined

**Comment by matevz** [comment] 2021-11-04 10:02
Duplicate of https://github.com/oasisprotocol/oasis-wallet-web/issues/403

**Closed by matevz** 2021-11-04 10:02 UTC
Labels: duplicate
