### ISSUE TITLE
ERROR Issue

### ISSUE THREAD

**Issue by swyche** [oasisprotocol/oasis-wallet-web#399] opened 2021-11-04 08:54 UTC
A fatal error occurred
A fatal unexpected error has occurred and Oasis-wallet must stop. Please copy report this issue below on our github account. You can also try refreshing page to see if the issue persists. Once you leave this page, all of your wallets will be closed.
The above error occurred in task Za
    created by Xa
    created by takeEvery(staking/fetchAccount, Xa)
    created by er
Tasks cancelled due to error:
takeEvery(staking/fetchAccount, Xa)
takeEvery(staking/validatorSelected, Qa)

**Comment by matevz** [comment] 2021-11-04 09:57
Duplicate of https://github.com/oasisprotocol/oasis-wallet-web/issues/403

**Closed by matevz** 2021-11-04 09:57 UTC
Labels: duplicate, wontfix
